DATA_DIR = "./data"
MODEL_DIR = "./models"
CATEGORIES = [
    "apple",
    "carrot",
    "cat",
    "house",
    "umbrella",
    "airplane",
    "clock",
    "cloud",
    "star",
    "tree",
    "smiley face",
    "table",
    "pizza",
    "book",
    "computer",
    "ice cream",
    "floor lamp",
    "key",
    "pencil",
    "flower",
    "cake",
    "snowflake",
    "triangle",
    "square",
    "circle",
    "hamburger",
    "map",
    "moon",
    "pear",
    "blueberry",
    "bird",
    "sock",
    "zigzag",
    "compass",
    "cookie",
    "fish",
    "grapes",
    "jail",
    "lightning",
    "leaf",
    "snowman"
]
IMAGE_SIZE = 28